[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "echoes_project"
version = "0.1"
dependencies = [
    "F5_TTS",
    "sounddevice",
    "numpy",
]
